<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.yuku123</groupId>
        <artifactId>z-rpc</artifactId>
        <version>1.0.2</version>
    </parent>

    <groupId>io.github.yuku123</groupId>
    <version>1.0.2</version>

    <artifactId>z-rpc-common</artifactId>
    <name>z-rpc-common</name>
    <description>Common utilities (URL, Node, RpcException, Result) for Z-RPC.</description>

    <url>https://github.com/yuku123/z-rpc</url>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>yuku123</id>
            <name>yuku123</name>
            <email>1340947819@qq.com</email>
            <organization>z-team</organization>
            <organizationUrl>https://github.com/yuku123</organizationUrl>
            <timezone>+08:00</timezone>
            <roles>
                <role>owner</role>
            </roles>
        </developer>
    </developers>
    <scm>
        <connection>scm:git:https://github.com/yuku123/z-rpc.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/yuku123/z-rpc.git</developerConnection>
        <url>https://github.com/yuku123/z-rpc</url>
        <tag>HEAD</tag>
    </scm>


    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.yuku123</groupId>
            <artifactId>z-util-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
