server:
  port: 20890
  servlet:
    context-path: /

spring:
  application:
    name: order-service

z:
  rpc:
    enabled: true
    application:
      name: order-service
      version: 1.0.0
      organization: zifang
    registry:
      address: 127.0.0.1:8084
      type: z-config
      enabled: true
    consumer:
      timeout: 3000
      retries: 2
      loadbalance: random
      cluster: failover
      serialization: hessian2

logging:
  level:
    com.zifang.z.rpc: INFO
    com.zifang.demo: DEBUG
